### Create a new User
POST http://127.0.0.1:3000/register
Content-Type: application/json

{
    "name": "Emmanuel",
    "email": "dev@gmail.com",
    "password": "12345678",
    "age": 18,
    "field": "anything"
}


### Login
POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "email": "dev@gmail.com",
    "password": "12345678"
}

### Get User Profile
GET http://127.0.0.1:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MDk1NjE3MSwiZXhwIjoxNzYzNTQ4MTcxfQ.H5KXJgR50vm54x-5eiNFNoBX5Tquz6KuInBuFQJ9alo


### Update User Profile (Email cannot be changed)
PUT http://127.0.0.1:3000/edit-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MDk1NjE3MSwiZXhwIjoxNzYzNTQ4MTcxfQ.H5KXJgR50vm54x-5eiNFNoBX5Tquz6KuInBuFQJ9alo

{
    "name": "John David",
    "age": 28,
    "field": "Software Engineering"
}


### Change Password (Authenticated User)
PUT http://127.0.0.1:3000/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MDk1NjE3MSwiZXhwIjoxNzYzNTQ4MTcxfQ.H5KXJgR50vm54x-5eiNFNoBX5Tquz6KuInBuFQJ9alo

{
    "oldPassword": "12345678",
    "newPassword": "newpassword123"
}


### Forgot Password (Request Reset Token)
POST http://127.0.0.1:3000/forgot-password
Content-Type: application/json

{
    "email": "dev@gmail.com"
}


### Reset Password (Using Token)
POST http://127.0.0.1:3000/reset-password
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MDk1NjMzNiwiZXhwIjoxNzYwOTU3MjM2fQ.sZJWckllulT5fyL2ERJPuz9afa4u1NZXQB2GDBNgniQ",
    "newPassword": "12345678"
}
