### sign-up
post http://127.0.0.1:3000/api/auth/signup
Content-Type: application/json

  {
    "name": "Dr. Daniel Ojo",
    "email": "daniel.ojo@cityhospital.com",
    "password": "DanjO!88",
    "role": "doctor",
    "phone": "07012349876",
    "specialization": "Ophthalmology",
    "bio": "Ophthalmologist skilled in cataract surgery and comprehensive eye care.",
    "experience": 14,
    "consultationFee": 260.00
  }

### log-in
post http://127.0.0.1:3000/api/auth/login
Content-Type: application/json

{
  "email": "emmanuel@dr.com", 
  "password": "12345678"
}

### Get all doctors
GET http://127.0.0.1:3000/api/doctors


### Get doctors Profile
GET http://127.0.0.1:3000/api/doctors/3

### Get doctors Profile
PUT http://127.0.0.1:3000/api/doctors/availability
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6ImRvY3RvciIsImlhdCI6MTc2MjQyNTgxNiwiZXhwIjoxNzYzMDMwNjE2fQ.04AJqjr0zy4WtxWeEo0Ia_Qh4DlUAB3nfJwrpSl7zxA
Content-Type: application/json

{
  "availableSlots": {
    "Mon": true,
    "Tue": true,
    "Wed": true,
    "Thu": false,
    "Fri": true,
    "Sat": false,
    "Sun": false,
    "startTime": "09:00 AM",
    "endTime": "02:00 PM"
  }
}


### Profile
GET http://127.0.0.1:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6ImRvY3RvciIsImlhdCI6MTc2MjQyNTgxNiwiZXhwIjoxNzYzMDMwNjE2fQ.04AJqjr0zy4WtxWeEo0Ia_Qh4DlUAB3nfJwrpSl7zxA
